### ISSUE TITLE
NSL-KDD

### ISSUE THREAD

**Issue by notti** [CN-TU/nta-meta-analysis#22]
https://github.com/CN-TU/nta-meta-analysis/blob/3ea20423a3a4d69cc7ccb9bad2ded1873dffc427/v2_papers/2017/bamakan_ramp.json#L31-L38

Wasn't this dataset generated in [2009](http://www.unb.ca/cic/datasets/nsl.html)? Well it is based on KDD'99 dataset - but shouldn't this be the year the used data was generated?

**Comment by notti** [comment]
See also
https://github.com/CN-TU/nta-meta-analysis/blob/95e95da5b8a8a8b0854429a2cb5c365277c90931/v2_papers/2017/ashfaq_fuzziness.json#L37
https://github.com/CN-TU/nta-meta-analysis/blob/95e95da5b8a8a8b0854429a2cb5c365277c90931/v2_papers/2016/ambusaidi_building.json#L59
https://github.com/CN-TU/nta-meta-analysis/blob/c5b991a2c7bf564bf3d661791f17e5561084f7d8/v2_papers/2012/zargari_feature.json#L36
https://github.com/CN-TU/nta-meta-analysis/blob/c5b991a2c7bf564bf3d661791f17e5561084f7d8/v2_papers/2013/zhang_aneffective.json#L36
https://github.com/CN-TU/nta-meta-analysis/blob/c5b991a2c7bf564bf3d661791f17e5561084f7d8/v2_papers/2016/javaid_adeep.json#L38

vs

https://github.com/CN-TU/nta-meta-analysis/blob/95e95da5b8a8a8b0854429a2cb5c365277c90931/datasets.json#L44-L49

**Comment by felixig** [comment]
I agree.

 

Best,

 

F


 

Gesendet: Freitag, 20. April 2018 um 09:13 Uhr
Von: "Gernot Vormayr" <notifications@github.com>
An: CN-TU/nta-meta-analysis <nta-meta-analysis@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [CN-TU/nta-meta-analysis] NSL-KDD (#22)


https://github.com/CN-TU/nta-meta-analysis/blob/3ea20423a3a4d69cc7ccb9bad2ded1873dffc427/v2_papers/2017/bamakan_ramp.json#L31-L38

Wasn't this dataset generated in 2009? Well it is based on KDD'99 dataset - but shouldn't this be the year the used data was generated?

**Comment by dcferreira** [comment]
I agree also. I guess what makes sense for this field is the when the data is from, and not when the packets are from.
